### ISSUE TITLE
git 2.23 log empty

### ISSUE THREAD

**Issue by miaomiaozhou88** [Anaconda-Platform/anaconda-project#240]
while using anaconda with git 2.23, the git log is always empty. would you please help? I am using windows 8.

**Comment by AlbertDeFusco** [comment]
That problem seems unlikely to be related to conda, but in any case anaconda-project is a command-line tool for capturing reproducible projects; it is not "anaconda" or "conda" in general. In future, if your issue is with:

* the conda command: See https://github.com/conda/conda/issues
* repo.anaconda.com or a package from the Anaconda defaults channel: See https://github.com/ContinuumIO/anaconda-issues
* anaconda.org access and service: See https://anaconda.org/contact/report
* Anaconda as a company: See https://www.anaconda.com/contact
