### ISSUE TITLE
referring to custom channels for a specific reference to a dependency

### ISSUE THREAD

**Issue by njesp** [Anaconda-Platform/anaconda-project#259]
I originally formulated this as question on [stackoverflow](https://stackoverflow.com/questions/58743707/how-can-i-configure-an-anaconda-environment-to-pull-specific-packages-from-separ). 

The question was quite popular, but did not elicit any replies. I still need to know a way to do this, so now I give it a shot here.

Thank you

Niels Jespersen

**Comment by AlbertDeFusco** [comment]
That problem seems more related to conda, but in any case anaconda-project is a command-line tool for capturing reproducible projects; it is not "anaconda" or "conda" in general. In future, if your issue is with:

* the conda command: See https://github.com/conda/conda/issues
* repo.anaconda.com or a package from the Anaconda defaults channel: See https://github.com/ContinuumIO/anaconda-issues
* anaconda.org access and service: See https://anaconda.org/contact/report
* Anaconda as a company: See https://www.anaconda.com/contact
