### ISSUE TITLE
[BUG] ext4_lookup:1706: inode #44565329: comm conda: iget: bad extra_isize 9234 (inode size 256)

### ISSUE THREAD

**Issue by Shivanshu10** [Anaconda-Platform/anaconda-project#315]
I'm using conda on my kali machine, Often on running my terminal my filesystem gets read only and on checking disk logs I found some errors
```
ext4_lookup:1706: inode #44565329: comm conda: iget: bad extra_isize 9234 (inode size 256)
```
so is this due to some issue my conda env

**Comment by jbednar** [comment]
That problem seems unlikely to be related to conda, but in any case anaconda-project is a command-line tool for capturing reproducible projects; it is not "anaconda" or "conda" in general. In future, if your issue is with:

- repo.anaconda.com or a package from the Anaconda defaults channel: See https://github.com/ContinuumIO/anaconda-issues
- anaconda.org access and service: See https://anaconda.org/contact/report
- Anaconda as a company: See https://www.anaconda.com/contact
