### ISSUE TITLE
Want to link/Register copied conda environment.

### ISSUE THREAD

**Issue by Psp29onetwo** [Anaconda-Platform/anaconda-project#350]
**Is your feature request related to a problem? Please describe.**
I've moved my conda env to another folder and I want to register or link that moved conda env which I think is not possible after I did a google search.

**Describe the solution you'd like**
The best solution will be a conda command to verify env required files and the register that env into conda like :

> conda register [..path/to/env/directory]

or

> conda link [..path/to/env/directory]

**Describe alternatives you've considered**
Just want to add new command might be no alternatives, no that I know.

**Comment by jbednar** [comment]
This would be a request for [conda's issue tracker](https://github.com/conda/conda), not anaconda-project, but in any case conda can't support this directly because the unpacked environment is not relocatable; it has paths encoded directly into the contents of that directory. You can use [conda-pack](https://conda.github.io/conda-pack) to make relocatable environments, though!

**Comment by Psp29onetwo** [comment]
@jbednar Thanks ill request conda for this feature, also thank you for mentioning the conda pack.
