### ISSUE TITLE
'conda update conda' leads to CondaHTTPError: HTTP 401 UNAUTHORIZED

### ISSUE THREAD

**Issue by majkelx** [Anaconda-Platform/anaconda-project#42]
I've just tried tu upgrate anaconda following [documentation](https://docs.continuum.io/anaconda/install#updating-from-older-anaconda-versions).

```
$ conda update conda
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment //anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    requests-2.13.0            |           py35_0         812 KB
    cryptography-1.7.1         |           py35_0         479 KB
    pyopenssl-16.2.0           |           py35_0          70 KB
    conda-4.3.14               |           py35_0         505 KB
    ------------------------------------------------------------
                                           Total:         1.8 MB

The following packages will be UPDATED:

    conda:        4.2.11-py35_0 --> 4.3.14-py35_0
    cryptography: 1.3-py34_0    --> 1.7.1-py35_0 
    pyasn1:       0.1.9-py34_0  --> 0.1.9-py35_0 
    pyopenssl:    0.15.1-py34_2 --> 16.2.0-py35_0
    requests:     2.9.1-py35_0  --> 2.13.0-py35_0

Proceed ([y]/n)? y

Fetching packages ...
requests-2.13. 100% |####################################################################################################################################| Time: 0:00:01 589.91 kB/s
cryptography-1 100% |####################################################################################################################################| Time: 0:00:00 801.18 kB/s
pyopenssl-16.2 100% |####################################################################################################################################| Time: 0:00:00 168.23 kB/s
conda-4.3.14-p 100% |####################################################################################################################################| Time: 0:00:01 415.30 kB/s
Extracting packages ...
[      COMPLETE      ]|#######################################################################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|#######################################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|#######################################################################################################################################################| 100%
```
Then tried to update `anaconda`:
```
$ conda update anaconda
Fetching package metadata ...

CondaHTTPError: HTTP 401 UNAUTHORIZED for url <https://conda.anaconda.org/auto/osx-64/repodata.json>
Elapsed: 00:00.358280
CF-RAY: 33efe5abae435954-VIE

The remote server has indicated you are using invalid credentials for this channel.

If the remote site is anaconda.org or follows the Anaconda Server API, you
will need to
  (a) login to the site with `anaconda login`, or
  (b) provide conda with a valid token directly.

Further configuration help can be found at <https://conda.io/docs/config.html>.
```
Any operation on `anaconda` ends as follows:
```
$ anaconda whoami
Traceback (most recent call last):
  File "//anaconda/bin/anaconda", line 4, in <module>
    import binstar_client.scripts.cli
ImportError: No module named 'binstar_client'
```
But of course 
```
$ conda install binstar
Fetching package metadata ...

CondaHTTPError: HTTP 401 UNAUTHORIZED for url <https://conda.anaconda.org/auto/osx-64/repodata.json>
Elapsed: 00:01.077387
CF-RAY: 33f00d4ddb9559c0-VIE
```
[...]
I've no idea what to do.

**Comment by majkelx** [comment]
`conda info` works:
```
$ conda info
Current conda install:

               platform : osx-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.13.0
       root environment : //anaconda  (writable)
    default environment : //anaconda
       envs directories : //anaconda/envs
                          /Users/mka/.conda/envs
          package cache : //anaconda/pkgs
                          /Users/mka/.conda/pkgs
           channel URLs : https://conda.anaconda.org/auto/osx-64
                          https://conda.anaconda.org/auto/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/mka/.condarc
           offline mode : False
             user-agent : conda/4.3.14 requests/2.13.0 CPython/3.5.2 Darwin/16.4.0 OSX/10.12.3
                UID:GID : 502:20
```

**Comment by ijstokes** [comment]
That is a pretty weird error message.  I'd suggest reporting it to:

https://github.com/ContinuumIO/anaconda-issues/issues/new

It looks like a bug on our side.  If it were me and I were trying to 
work around it I would do the following:

conda update conda
conda update anaconda-client
conda update requests

And then try again.  It is painful that we still have a Python package 
called "binstar" in Anaconda, especially since there is no corresponding 
Conda package related to this (TTBOMK) -- the Python package is 
contained inside the "anaconda-client" package (hence the update above).

But the error you are seeing suggests to me that those commands above 
may fail as well.

It is possible you have a borked base environment.  Anaconda 4.2 
actually *shipped* with a broken base environment (yes, this was an 
accident) but in most cases it would "self-heal" from a conda update 
(intentional, as above, or automatic, which is the default). However for 
some people (I am one of them) the borked base environment meant that 
things could go from a very little bit broken to a whole lot big 
broken.  The short explanation for why is that conda will always try to 
maintain all software dependencies unless you tell it not to.  If it 
STARTS with unsatisfied dependencies (e.g. virgin Anaconda 4.2 
installation) then conda will think "oh, this person has already decided 
to break dependencies and I won't try to fix it, so I'll just do the 
minimum, and let things stay broken".

If I had to guess I'd say you are in that situation, but I don't really 
know.  I'm offline right now otherwise I'd look for information on how 
you can do a consistency self-check to see if your environment is 
"valid" (all dependencies satisfied) or "broken" (dependencies unsatisfied).

Finally there is a chance that this issue is due to something on your 
side: local firewall, corporate proxy, ISP.  You might want to try 
gettin around that by doing your conda operations "anonymously" by 
logging out:

anaconda logout

That will then stop the anaconda-client from sending any user token to 
the server, which is where it looks like things are getting confused.

Please let us know if you resolve the issue, or (as suggested first) 
advance this to a GitHub support issue.

Regards,

Ian

**Comment by ijstokes** [comment]
This issue is in the wrong repo.  It should be added to https://github.com/conda/conda/issues/3780.  I responded via email thinking it was from the Anaconda ML.  Someone should swing it over there and close this one.
